### PR TITLE
add indexing option, closes #35

### LINKED ISSUE #35: index option on write stream
> •mafintosh> jhand: just noticed that https://github.com/juliangruber/hyperdrive-import-files/blob/master/index.js#L85 does not set indexing: true on the write stream
> •mafintosh> jhand: we should add an option for that. will speed up imports a lot

https://botbot.me/freenode/dat/2016-12-22/?msg=78342893&page=3

### PR DESCRIPTION
**Pull request by joehand**
Much faster imports. Yay!

### CODE REVIEW

**Comment by joehand** [comment]
This is passing in everything but node v5 because of prebuild issues. Should we move tests from v5 -> v7?

**Comment by juliangruber** [comment]
node 5 is still a required target, let's rather move this to the rabin repo to figure this out. I'll get this compiling

**Comment by juliangruber** [comment]
prebuilds were missing

**Comment by juliangruber** [comment]
2.6.0 :)

**Pull request merged**
