### PR TITLE
Do not store or check mtime for directories

### PR DESCRIPTION
**Pull request by joehand**
We were getting a lot of duplicate directory entries because of updated mtimes. 

This PR just adds directories once, not storing or checking mtimes.

### CODE REVIEW

**Comment by juliangruber** [comment]
While this might work, it's not correct. A directory's mtime can change and that should be reflected in hyperdrive.

Do we really want to diverge from the file system here?

**Comment by joehand** [comment]
Ya that makes sense if we want to replicate the filesystem. I think the concern is bloating the metadata. See conversation below with @mafintosh:

```
5:02 PM <•mafintosh> we might just not add folders actually. we mkdirp them anyway
5:03 PM <pfrazee> mafintosh: I've been planning to force folders to be explictly created in the dat web api
5:03 PM <•mafintosh> jhand: o/ i think there might be an issue with folders being re-added still
5:03 PM <pfrazee> that's how it's implemented now
5:03 PM <•mafintosh> pfrazee: makes a lot of sense. i was refering to how the cli adds it
5:04 PM <•mafintosh> for an api i'd def require a mkdir call
5:04 PM <pfrazee> mafintosh: yeah. My "read" code is tolerant of missing directory creations
5:05 PM <•mafintosh> jhand: also i wonder what is up with the empty folder haha. very likely my mistake somewhere
5:05 PM <•mafintosh> pfrazee: thats a decent trade-off
5:09 PM ↔ Alihoha popped in  
5:19 PM <•mafintosh> pfrazee: i need your feedback on a few crypto tweaks i wanna make at some point
5:19 PM <•mafintosh> i'll try and gist it soon
5:20 PM <jhand> huh. I wonder if we need to re-add directories at all. Duplicates just update the mtime in hyperdrive. Would it be better to not store mtime for dirs?
5:21 PM <•mafintosh> jhand: we should never re-add dirs yea
5:22 PM <jhand> makes sense, i'll update the importer
```

**Comment by mafintosh** [comment]
@juliangruber add an option perhaps. its bloating a lot archives right now in live mode which also not ideal.

**Comment by karissa** [comment]
should we merge this?

**Comment by juliangruber** [comment]
i'm going to publish this as a major together with https://github.com/juliangruber/hyperdrive-import-files/pull/44

**Comment by juliangruber** [comment]
unless we need this more quickly, since it looks like we want to test recursive-watch a bit more until we merge?

**Comment by joehand** [comment]
> unless we need this more quickly, since it looks like we want to test recursive-watch a bit more until we merge?

Sounds good, that was my thought too.

**Pull request merged**
