### PR TITLE
Upgrade hyperdrive

### PR DESCRIPTION
**Pull request by millette**
And fix test with fs.utimes().

### CODE REVIEW

**Comment by millette** [comment]
The test should pass once [hyperdrive-import-files#54](https://github.com/juliangruber/hyperdrive-import-files/pull/54) is approuved.

Technically, I should have replaced ```NaN``` with Date.now() according to [v4 docs](https://nodejs.org/dist/v4.8.6/docs/api/fs.html#fs_fs_utimes_path_atime_mtime_callback) but I don't think it changes the result of the test. The treatment of ```NaN``` changed in [v8](https://nodejs.org/dist/latest-v8.x/docs/api/fs.html#fs_fs_utimes_path_atime_mtime_callback).

**Comment by juliangruber** [comment]
do you mean this test should past once this pr is approved? i'm confused

**Comment by millette** [comment]
Doh! Should have said:

The test should pass once [hyperdrive-duplicate#2](https://github.com/joehand/hyperdrive-duplicate/pull/2) is approved.

**Comment by juliangruber** [comment]
Thanks for updating! Published as 4.0.0

**Pull request merged**
