### PR TITLE
Add resume test using raf (#12)

### PR DESCRIPTION
**Pull request by joehand**
PR adds a test, currently failing, for testing the mtime bug with raf and files on fs.

### CODE REVIEW

**Comment by joehand** [comment]
Passing with your hyperdrive PR! Amended my last commit with the correct `t.plan()` count.

**Comment by juliangruber** [comment]
W00P! Just need to get the hyperdrive PR merged now. cc @mafintosh hehehe

**Comment by joehand** [comment]
Bumped hyperdrive hoping that'd make the tests pass but Travis is still having trouble. 

These pass locally, maybe its the same travis bug you were having with the other tests?

**Comment by juliangruber** [comment]
the problem before was with life mode, maybe we can get resume to work though

**Comment by juliangruber** [comment]
i restarted the build and it passes now! woop woop

**Pull request merged**
